#!/bin/bash
# SpaceCat Local Testing Configuration
# This file is auto-generated by setup-spacecat-tools.sh
# Edit this file or re-run setup to change paths

# Path to spacecat-content-scraper directory
export SPACECAT_SCRAPER_DIR="/Users/jsanchez/Documents/GitHub/SPACECAT/spacecat-content-scraper"

# Path to spacecat-audit-worker directory
export SPACECAT_AUDIT_WORKER_DIR="/Users/jsanchez/Documents/GitHub/SPACECAT/spacecat-audit-worker"

# Path to my-workspace-tools directory (where these scripts live)
export SPACECAT_TOOLS_DIR="/Users/jsanchez/Documents/GitHub/SPACECAT/my-workspace-tools"

# Path to scraper's tmp folder (used by audit worker's mock S3 client)
export SPACECAT_SCRAPER_TMP_DIR="$SPACECAT_SCRAPER_DIR/tmp"

# Optional: Default SpaceCat API key (leave empty to prompt each time)
export SPACECAT_API_KEY="hebelehebele"

# ============================================================================
# You can manually edit the paths above or re-run: ./setup-spacecat-tools.sh
# ============================================================================
